### ISSUE TITLE
add it to Package Control

### ISSUE THREAD

**Issue by ctf0** [atelierbram/duotones-sublime-colorschemes#1]
DEFINITELY :metal:

**Comment by atelierbram** [comment]
Thanks for the heads up; just did a [pull request for this](https://github.com/wbond/package_control_channel/pull/5558)

**Comment by ctf0** [comment]
if u could also consider having a theme to complement the whole thing it would be perfect.

**Comment by atelierbram** [comment]
Yes, but ... priorities. First priority will be to also generate _light_ color-schemes from the templates, like it is done [over here for Prism](http://atelierbram.github.io/Base2Tone-prism/demo/desert/light/). So this will take some time to accomplish with [this newer implementation](https://github.com/atelierbram/Base2Tone) which means in a way starting all over. 

Anyway, maybe not essential, but if I would want to make a theme for Sublime Text it would probably be a hacked version or variations of this [Flatland theme](https://github.com/thinkpixellab/flatland), which I quite like.

**Comment by ctf0** [comment]
ooh , okay, good luck with that then 👍

**Comment by atelierbram** [comment]
PR [has been merged](https://github.com/wbond/package_control_channel/pull/5558) see [wbond/package_control_channel/repository/d.jsond.json](https://github.com/wbond/package_control_channel/blob/master/repository/d.json)

**Comment by ctf0** [comment]
thanx 💯
